force-app/main/default/objects/Contact/fields/Most_recent_payment_date__c.field-meta.xml
<CustomField>
    <fullName>Most_recent_payment_date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Most recent payment date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Amount_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount of Payments</label>
    <precision>15</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P{MM}{DD}{YYYY}{000000}</displayFormat>
        <label>PaymentNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Amount_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount of Payments</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentTriggerHandler.cls
public class PaymentTriggerHandler extends TriggerHandler {
    private List<Payments__c> newPaymentsList;
    private List<Payments__c> oldPaymentsList;

    public PaymentTriggerHandler() {
        this.newPaymentsList = Trigger.New;
        this.oldPaymentsList = Trigger.Old;
    }

    // Update Contact & Project field data given a Payment triggerAction
    private void updateAmounts(List<Payments__c> paymentsList,String triggerAction){
        // TODO: Query Factory
        Map<Id,Contact> contacts = new Map<Id,Contact>([SELECT Id, Total_Amount_of_Payments__c, Most_recent_payment_date__c FROM Contact]);
        Map<Id,Project__c> projects = new Map<Id,Project__c>([SELECT Id, Total_Amount_of_Payments__c FROM Project__c]);
            
        List<SObject> updatedObjs = new List<SObject>();
        
        for (Payments__c payment : paymentsList) {
            Contact ct = contacts.get(payment.Contact__c);
            Project__c pj = projects.get(payment.Project__c);

            switch on triggerAction {
                when 'insert' {
                    // Increment Total Amaunt of Payments & rewrite payment date
                    ct.Total_Amount_of_Payments__c += payment.Amount__c;
                    pj.Total_Amount_of_Payments__c += payment.Amount__c;
                    ct.Most_recent_payment_date__c = payment.Payment_Date__c;
                }
                when 'delete' {
                    // Decrement Total Amaunt of Payments
                    ct.Total_Amount_of_Payments__c -= payment.Amount__c;
                    pj.Total_Amount_of_Payments__c -= payment.Amount__c;
                }
                when 'update' {
                    // Get the old Payment Amount
                    Map<Id, Payments__c> oldPaymentsMap = new Map<Id, Payments__c>(oldPaymentsList);
                    Decimal oldPaymentAmount = oldPaymentsMap.get(payment.Id).Amount__c;

                    // Add up the Amount difference
                    ct.Total_Amount_of_Payments__c += payment.Amount__c - oldPaymentAmount;
                    pj.Total_Amount_of_Payments__c += payment.Amount__c - oldPaymentAmount;
                }
            }

            updatedObjs.add(ct);
            updatedObjs.add(pj);
        }
        update updatedObjs;
    }

    public override void afterInsert() {
        updateAmounts(newPaymentsList, 'insert');
    }

    public override void afterUpdate() {
        updateAmounts(newPaymentsList, 'update');
    }

    public override void afterDelete() {
        updateAmounts(oldPaymentsList, 'delete');
    }
}