force-app/main/default/objects/Contact/fields/Most_recent_payment_date__c.field-meta.xml
<CustomField>
    <fullName>Most_recent_payment_date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Most recent payment date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Amount_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount of Payments</label>
    <precision>15</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P{MM}{DD}{YYYY}{000000}</displayFormat>
        <label>PaymentNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContactController.cls
//CaseController.cls
public with sharing class ContactController {
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactPayments(){
        List<Contact> c =  [SELECT Name, Most_recent_payment_date__c, Total_Amount_of_Payments__c, 
                (SELECT Id, Name, Payment_Date__c, Amount__c from Payments__r) 
                FROM Contact WHERE Id IN (SELECT Contact__c FROM Payments__c)];
        return c;
    }
}